matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
        - openjdk8
      script:
        - gradle installDist
    - language: clojure
      before_script:
        - cd int-tests
      script:
        - lein run
