@Given("I have a thing.")
@When("I (do|give|have) a thing.")
@Then("\\(parens for trouble\\)")
@Given("\"quotes for trouble\"")
@When("\\\\backslashes for trouble\\\\")
@Then("the dog is on the (.*)")
@Given("the cat is on the ([A-Z]+)")
@Given("the regex is broken ([A-Z+)")
